### ISSUE TITLE
临时解决时区问题

### ISSUE THREAD

**Issue by QYG2297248353** [OwO-Network/DeepLX#110]
临时解决方案：
挂载系统时区文件，因此如果是使用windows等系统将无法使用
```yml
version: "3.8"

services:
  deeplx:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    # 其他配置
```

_Originally posted by @QYG2297248353 in https://github.com/OwO-Network/DeepLX/issues/109#issuecomment-2078790063_
